#!/bin/bash

# directory containing the source files
src_dir="/home/hackerskull/alx-low_level_programming/0x05-pointers_arrays_strings"
# directory where object files will be stored
obj_dir="0x09-static_libraries"

# make sure the obj dir exists
mkdir -p ${obj_dir}

# find all .c files in the src directory
for file in $(find ${src_dir} -name "*.c"); do
    # construct the corresponding object file path
    obj_file="${obj_dir}/${file%.c}.o"
    # create the directories for the object file
    mkdir -p $(dirname ${obj_file})
    # compile the source file into an object file
    gcc -c -o ${obj_file} ${file}
done
